export const MOVIE_DATA = {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/ciFHOyVlaMV2N7T44JOsj6his7P.jpg',
            genre_ids: [18, 36, 10752],
            id: 11165,
            original_language: 'en',
            original_title: 'Tora! Tora! Tora!',
            overview:
                'In the summer of 1941, the United States and Japan seem on the brink of war after constant embargos and failed diplomacy come to no end. "Tora! Tora! Tora!", named after the code words use by the lead Japanese pilot to indicate they had surprised the Americans, covers the days leading up to the attack on Pearl Harbor, which plunged America into the Second World War.',
            popularity: 10.08,
            poster_path: '/4Clc1z1dfpfB6GNWRJH8QuKgE8u.jpg',
            release_date: '1970-01-26',
            title: 'Tora! Tora! Tora!',
            video: false,
            vote_average: 7.1,
            vote_count: 340,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [18],
            id: 607291,
            original_language: 'fr',
            original_title: 'Pour Don Carlos',
            overview:
                'Pour Don Carlos was the biggest production by Société des Films Musidora (est. December 10, 1919). Based on a novel by Pierre Benoît, Musidora’s first creatively autonomous work is set during the conflict between Carlists and Bourbons in late 19th century Spain. Benoît insisted that Jacques Lasseyne, a Spanish grandee who put money into the production, should co-direct. The film was shot in 1920, in the Spanish Basque Country. It represents a turning point in Musidora’s career, sparking her passionate love affair with a country and a culture that welcomed her as a great star. Above all, though, she encountered Antonio Cañero, a bullfighter who acted as her technical adviser on the film. Because of him, she did all she could to ensure that her succeeding productions, until 1926, were shot in Spain. Pour Don Carlos was released in Paris and in Madrid in December 1921, in a shortened version because its original, three-hour length made it impossible to release in the market of the time.',
            popularity: 0.6,
            poster_path: '/rdFKxgdYITyloOyok7ezNpaAAnW.jpg',
            release_date: '1921-12-01',
            title: 'For Don Carlos',
            video: false,
            vote_average: 0,
            vote_count: 0,
        },
        {
            adult: false,
            backdrop_path: '/jiRqbu0DiOe170Ss5NczQvv185T.jpg',
            genre_ids: [12, 16, 10751],
            id: 136368,
            original_language: 'th',
            original_title: 'เอคโค่ จิ๋วก้องโลก',
            overview:
                "Story of the adventures of three young men from two of the world's metropolis, New State Trinity Capital and Karen village in Northern Thailand. To help save the world from disaster recovery due to global warming.",
            popularity: 2.373,
            poster_path: '/pt2SbE1UHMtrX69jAqHMIfPYdXQ.jpg',
            release_date: '2012-08-01',
            title: 'Adventure Planet',
            video: false,
            vote_average: 5,
            vote_count: 12,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [18],
            id: 60101,
            original_language: 'en',
            original_title: 'Le Candidat',
            overview: '\r\n',
            popularity: 2.491,
            poster_path: '/sNT7RI9oWIxlxWJ5B4y2iAda5ki.jpg',
            release_date: '2007-04-11',
            title: 'The Candidate',
            video: false,
            vote_average: 5.4,
            vote_count: 11,
        },
        {
            adult: false,
            backdrop_path: '/hFnl4g3ORWZBJVapj4KwXVBHAyh.jpg',
            genre_ids: [18],
            id: 31345,
            original_language: 'fr',
            original_title: "L'Enfance nue",
            overview:
                "Handed over to foster care by his mother—who's unwilling to give up permanent custody—the now-adolescent François understands that nothing in life is permanent, and his increasingly erratic actions reflect this knowledge.",
            popularity: 4.56,
            poster_path: '/2cD6WpamMeCdMoinljqnj5c6YrF.jpg',
            release_date: '1968-04-03',
            title: 'Naked Childhood',
            video: false,
            vote_average: 7.2,
            vote_count: 40,
        },
        {
            adult: false,
            backdrop_path: '/A89qKnhI2UiqdnmbsCd6v1ussvQ.jpg',
            genre_ids: [18, 10749],
            id: 39415,
            original_language: 'fr',
            original_title: 'Loulou',
            overview:
                'Nelly, a restless young woman abandons her bourgeois friends and a steady relationship for the unemployed wild, leather-clad bad boy Loulou, whose charms include focusing his energy into sex.',
            popularity: 5.506,
            poster_path: '/gudzcFDfwOSJflUDWgbA50ahILS.jpg',
            release_date: '1980-09-03',
            title: 'Loulou',
            video: false,
            vote_average: 6.4,
            vote_count: 52,
        },
        {
            adult: false,
            backdrop_path: '/skSyYCSpacsmblOkBeUzK4NmNOy.jpg',
            genre_ids: [10749, 18],
            id: 63230,
            original_language: 'fr',
            original_title: 'Nous ne vieillirons pas ensemble',
            overview:
                "Jean has been married to Francoise for years, but his relationship with his wife has been all but over for a long time. She's hardly ever around, always traveling to Russia for work, and she drifts in and out of the film as well, reflecting the ephemeral nature of their marriage.",
            popularity: 4.176,
            poster_path: '/bwGa43RE2AaBMpoU2Jdlj08rK7.jpg',
            release_date: '1972-05-03',
            title: "We Won't Grow Old Together",
            video: false,
            vote_average: 7.1,
            vote_count: 42,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [27],
            id: 43585,
            original_language: 'en',
            original_title: 'Headless Horseman',
            overview:
                'Seven college kids take a shortcut on their way to a party and unfortunately end up in Wormwood – a "lost" town in the middle of nowhere. They find something strange and sinister happening there – bones and weird decorations line Main Street. The cause: local Wormwood legend says on All Hallows Eve one hundred years ago, a crazed man tortured the youngsters in town and then cut off their heads. In retaliation, the townspeople killed him by cutting off his head. Seeking revenge every seven years, he returns and takes seven heads from children in the town. Now the seven visitors find themselves hunted one by one as the Headless Horseman claims his due.',
            popularity: 10.766,
            poster_path: '/epDv0AW4qUbxqVHCiX1M5tzwxfn.jpg',
            release_date: '2007-10-27',
            title: 'Headless Horseman',
            video: false,
            vote_average: 6,
            vote_count: 17,
        },
        {
            adult: false,
            backdrop_path: '/3cyjYtLWCBE1uvWINHFsFnE8LUK.jpg',
            genre_ids: [12, 14, 16, 28, 10751, 10749],
            id: 10515,
            original_language: 'ja',
            original_title: '天空の城ラピュタ',
            overview:
                'A young boy and a girl with a magic crystal must race against pirates and foreign agents in a search for a legendary floating castle.',
            popularity: 26.433,
            poster_path: '/npOnzAbLh6VOIu3naU5QaEcTepo.jpg',
            release_date: '1986-08-02',
            title: 'Castle in the Sky',
            video: false,
            vote_average: 8,
            vote_count: 2755,
        },
        {
            adult: false,
            backdrop_path: '/4VAZwbPqy8nuL15JhTz1CwBxV2L.jpg',
            genre_ids: [12, 14, 18],
            id: 587,
            original_language: 'en',
            original_title: 'Big Fish',
            overview:
                'Throughout his life Edward Bloom has always been a man of big appetites, enormous passions and tall tales. In his later years, he remains a huge mystery to his son, William. Now, to get to know the real man, Will begins piecing together a true picture of his father from flashbacks of his amazing adventures.',
            popularity: 17.967,
            poster_path: '/tjK063yCgaBAluVU72rZ6PKPH2l.jpg',
            release_date: '2003-12-25',
            title: 'Big Fish',
            video: false,
            vote_average: 7.8,
            vote_count: 5494,
        },
        {
            adult: false,
            backdrop_path: '/tzk0DY0jZ9PMasfUXtpShGZf1XA.jpg',
            genre_ids: [12, 35, 18],
            id: 59050,
            original_language: 'it',
            original_title: 'La voce della luna',
            overview:
                'A parable on the whisperings of the soul that only madmen and vagabonds are capable of hearing. The odd couple, Ivo Salvini, a fake inspector of wells, and Gonnella, a former prefect, wander through the Emilia-Romagna countryside and discover a dystopia of television commercials, fascism, beauty pageants, rock music, Catholicism, and pagan rituals.',
            popularity: 6.334,
            poster_path: '/1E9bSjMK72pqYvpPioFuQd3IUBx.jpg',
            release_date: '1990-03-05',
            title: 'The Voice of the Moon',
            video: false,
            vote_average: 6.9,
            vote_count: 78,
        },
        {
            adult: false,
            backdrop_path: '/tZh2Db1uctBxLjW8l2IZXz8GdwE.jpg',
            genre_ids: [18, 35],
            id: 1611,
            original_language: 'de',
            original_title: 'Das Wunder von Bern',
            overview:
                'The movie deals with the championship-winning German soccer team of 1954. Its story is linked with two others: The family of a young boy is split due to the events in World War II, and the father returns from Russia after eleven years. The second story is about a reporter and his wife reporting from the tournament.',
            popularity: 8.302,
            poster_path: '/ujNucP3lk3VpJAswjNBUc0DYHPT.jpg',
            release_date: '2003-10-15',
            title: 'The Miracle of Bern',
            video: false,
            vote_average: 6.4,
            vote_count: 114,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 198497,
            original_language: 'fr',
            original_title: 'Neige',
            overview:
                'This drama about a barmaid caught up in events beyond her control is the first film directed by Juliet Berto, and was also based on her own concept for the story. The barmaid, played by Berto, has been trying to take care of Bobby, a teenage drug pusher who is in over his head. Before she can put him back on track and get him out of the drug underworld, the young man is killed while being chased by a narcotics agent. Depressed by his death but not derailed, she finds herself trying to help out a gay user who depended on Bobby for his supply of drugs. She decides to procure some drugs for the desperate addict, and is trapped in the bathroom of a bar - with the drugs - when narcotics agents burst upon the scene. Her boyfriend rushes to help her but is killed by an agent who shoots first and thinks later. The barmaid does not face a very optimistic future as the narc arrests her - but releases a parish minister who had been helping her find a source for the drugs.',
            popularity: 2.236,
            poster_path: '/hR88oqtvltRiGqJoL9BFLBRKxa.jpg',
            release_date: '1981-06-04',
            title: 'Snow',
            video: false,
            vote_average: 5.8,
            vote_count: 7,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 225461,
            original_language: 'en',
            original_title: 'The Scorpio Factor',
            overview:
                'In this espionage adventure, an Interpol agent must find a valuable stolen microchip. Soon he finds himself involved with beautiful women, fast cars, and danger on the exciting streets of Paris and New York.',
            popularity: 0.87,
            poster_path: null,
            release_date: '1989-01-01',
            title: 'The Scorpio Factor',
            video: false,
            vote_average: 3,
            vote_count: 1,
        },
        {
            adult: false,
            backdrop_path: '/3KwAmIKMaDcBMonF5wmyNTL0SR6.jpg',
            genre_ids: [18],
            id: 510,
            original_language: 'en',
            original_title: "One Flew Over the Cuckoo's Nest",
            overview:
                'While serving time for insanity at a state mental hospital, implacable rabble-rouser, Randle Patrick McMurphy, inspires his fellow patients to rebel against the authoritarian rule of head nurse, Mildred Ratched.',
            popularity: 19.379,
            poster_path: '/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg',
            release_date: '1975-11-18',
            title: "One Flew Over the Cuckoo's Nest",
            video: false,
            vote_average: 8.4,
            vote_count: 7667,
        },
        {
            adult: false,
            backdrop_path: '/shqLeIkqPAAXM8iT6wVDiXUYz1p.jpg',
            genre_ids: [16, 10751],
            id: 12429,
            original_language: 'ja',
            original_title: '崖の上のポニョ',
            overview:
                "The son of a sailor, 5-year old Sosuke lives a quiet life on an oceanside cliff with his mother Lisa. One fateful day, he finds a beautiful goldfish trapped in a bottle on the beach and upon rescuing her, names her Ponyo. But she is no ordinary goldfish. The daughter of a masterful wizard and a sea goddess, Ponyo uses her father's magic to transform herself into a young girl and quickly falls in love with Sosuke, but the use of such powerful sorcery causes a dangerous imbalance in the world. As the moon steadily draws nearer to the earth and Ponyo's father sends the ocean's mighty waves to find his daughter, the two children embark on an adventure of a lifetime to save the world and fulfill Ponyo's dreams of becoming human.",
            popularity: 111.703,
            poster_path: '/yp8vEZflGynlEylxEesbYasc06i.jpg',
            release_date: '2008-07-19',
            title: 'Ponyo',
            video: false,
            vote_average: 7.7,
            vote_count: 2735,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [],
            id: 559935,
            original_language: 'en',
            original_title: 'Giselle by Jean Coralli and Jules Perrot',
            overview:
                "Giselle, the Romantic ballet par excellence! Relive the story of a young country girl's innocent love for the Duke Albrecht. When she learns that he is already engaged to marry a princess, Giselle suffers violent hallucinations and then dies. In vengeance, the Queen of the Wilis—the ghosts of young girls who die before their time—condemns Albrecht to dance until he dies of exhaustion...",
            popularity: 0.6,
            poster_path: '/bV08kXyYA6KP9OlELILGMSi1lWe.jpg',
            release_date: '2007-01-01',
            title: 'Giselle by Jean Coralli and Jules Perrot',
            video: false,
            vote_average: 0,
            vote_count: 0,
        },
        {
            adult: false,
            backdrop_path: '/sE3bw3SF4ZwhAFdpw0MXQDpN3eI.jpg',
            genre_ids: [35, 12, 14, 878, 28],
            id: 11551,
            original_language: 'en',
            original_title: 'Small Soldiers',
            overview:
                'When missile technology is used to enhance toy action figures, the toys soon begin to take their battle programming too seriously.',
            popularity: 20.665,
            poster_path: '/2nuUjSzHsoYlRvTPmLo7m7gCQry.jpg',
            release_date: '1998-07-10',
            title: 'Small Soldiers',
            video: false,
            vote_average: 6.5,
            vote_count: 1492,
        },
        {
            adult: false,
            backdrop_path: '/oOSRhoplrujWiPgxG1ww6b9dbR5.jpg',
            genre_ids: [18, 14],
            id: 98864,
            original_language: 'en',
            original_title: 'Resurrection',
            overview:
                'The story of a woman who survives the car accident which kills her husband, but discovers that she has the power to heal other people. She becomes an unwitting celebrity, the hope of those in desperate need of healing, and a lightning rod for religious beliefs and skeptics.',
            popularity: 5.162,
            poster_path: '/8Oq0lF2a0Cqzp5NA8spLPola0lN.jpg',
            release_date: '1980-09-26',
            title: 'Resurrection',
            video: false,
            vote_average: 6.8,
            vote_count: 23,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [18],
            id: 215378,
            original_language: 'en',
            original_title: 'Americana',
            overview:
                'In a small town in rural Kansas, a troubled veteran attempts to restore an old merry-go-round ride.',
            popularity: 0.984,
            poster_path: '/ccSeFmYJTZc4isX2Bdqwy8pm37M.jpg',
            release_date: '1981-05-16',
            title: 'Americana',
            video: false,
            vote_average: 5.7,
            vote_count: 3,
        },
    ],
    total_pages: 500,
    total_results: 10000,
}

export const DETAIL_DATA = {
    adult: false,
    backdrop_path: '/nOK6mVgBUkt7IVSfesVVJd4i5uU.jpg',
    belongs_to_collection: {
        id: 427084,
        name: 'The Secret Life of Pets Collection',
        poster_path: '/d83LVydlQonKdshwQyLYx48D3LH.jpg',
        backdrop_path: '/lB4l8H0jgPp2bf4NV2aZPIyytdQ.jpg',
    },
    budget: 75000000,
    genres: [
        {
            id: 12,
            name: 'Adventure',
        },
        {
            id: 35,
            name: 'Comedy',
        },
        {
            id: 16,
            name: 'Animation',
        },
        {
            id: 10751,
            name: 'Family',
        },
    ],
    homepage: 'http://www.thesecretlifeofpets.com/',
    id: 328111,
    imdb_id: 'tt2709768',
    original_language: 'en',
    original_title: 'The Secret Life of Pets',
    overview:
        'The quiet life of a terrier named Max is upended when his owner takes in Duke, a stray whom Max instantly dislikes.',
    popularity: 31.261,
    poster_path: '/gJo9G56QlXKRe2tcdDVSt28xVsP.jpg',
    production_companies: [
        {
            id: 33,
            logo_path: '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
            name: 'Universal Pictures',
            origin_country: 'US',
        },
        {
            id: 3341,
            logo_path: '/dTG5dXE1kU2mpmL9BNnraffckLU.png',
            name: 'Fuji Television Network',
            origin_country: 'JP',
        },
        {
            id: 6704,
            logo_path: '/fOG2oY4m1YuYTQh4bMqqZkmgOAI.png',
            name: 'Illumination Entertainment',
            origin_country: 'US',
        },
        {
            id: 1778,
            logo_path: '/69xm6sF3JxugGVjfZfm1YY6d7EE.png',
            name: 'DENTSU',
            origin_country: 'JP',
        },
    ],
    production_countries: [
        {
            iso_3166_1: 'US',
            name: 'United States of America',
        },
    ],
    release_date: '2016-06-18',
    revenue: 875457937,
    runtime: 87,
    spoken_languages: [
        {
            english_name: 'English',
            iso_639_1: 'en',
            name: 'English',
        },
    ],
    status: 'Released',
    tagline: 'Think this is what they do all day?',
    title: 'The Secret Life of Pets',
    video: false,
    vote_average: 6.2,
    vote_count: 6687,
}
